name: Proxy Checker

on:
  schedule:
    - cron: '*/80 * * * *'
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        
    - name: Install dependencies
      run: npm install
        
    - name: Check proxies
      run: |
        node proxy-checker.js
      env:
        OUTPUT_FILE: working_proxies.txt
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update working_proxies.txt
        file_pattern: working_proxies.txt
